name = "Razon Yang"
# avatar = "images/profile.png" # Avatar image.
bio = "Gopher, PHPer, Full Stack Engineer."
# company = ""
location = "China"

[social]
  email = "razonyang@gmail.com"
  github = "razonyang"
  # gitlab = "razonyang"
  twitter = "razonyang"
  telegram = "razonyang"
  qq = "919680596"
