baseurl = "/"
title = "Razon Yang"
author = "Razon Yang"
theme = "hugo-theme-bootstrap"
copyright = "Copyright Â© 2016-{year} Razon Yang. All Rights Reserved."

defaultContentLanguage = "zh-cn"
defaultContentLanguageInSubdir = true

enableRobotsTXT = true

enableEmoji = true

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
