author = "Razon Yang"
brand = "RAZON YANG"
palette = "indigo"
description = "Web 开发技术博客"

mainSections = ["posts"]

recentPostCount = 5
featuredPostCount = 5

customCSS = [
]
customJS = [
]

[beian]
  no = "粤公网安备44040302000341号"
  link = "http://www.beian.gov.cn/portal/registerSystemInfo?recordcode=44040302000341"
  icpNo = "粤ICP备20043980号"
  icpLink = "http://beian.miit.gov.cn/"

[reward]
  wechat = "/images/reward/wechat.webp"
  alipay = "/images/reward/alipay.webp"

[pwa]
  [pwa.minifest]
    short_name = "Razon"

[contact]
  endpoint = "https://formspree.io/f/mnqwqgvr"

[creativeCommons]
  # by = true # Credit must be given to you, the creator.
  # nc = true # Only noncommercial use of your work is permitted.
  # nd = true # No derivatives or adaptations of your work are permitted.
  # sa = true # Adaptations must be shared under the same terms.
